#!/usr/bin/env python3
"""Writes Sources/LodestarCore/ColorNameData.swift from the xkcd color survey.

rgb.txt is the survey's result (https://xkcd.com/color/rgb.txt, CC0): the
949 names more than 200,000 people most often gave colors on their own screens,
each at the color they gave it to. It is the accurate half of a name; the
curation below is the character half. Out go the crude (a clip strip is
looked at every day), the judgmental (a color someone chose is not ugly),
brands and characters, misspellings, joke words, bare suffixes, and names
jammed together or split by a slash that repeat a spaced one. Two names are
added at their published values: International Orange, the accent Lodestar
already calls by that name, and Klein Blue.

    python3 tools/color-names/curate.py
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "..", "Sources", "LodestarCore", "ColorNameData.swift")

DENY = {
    # crude
    "booger", "booger green", "baby shit brown", "baby puke green", "shit green", "poop green",
    "piss yellow", "barf green", "baby shit green", "diarrhea", "puke brown", "baby poo",
    "vomit yellow", "baby poop green", "snot", "poo", "baby poop", "poo brown", "poop brown",
    "shit brown", "shit", "snot green", "puke yellow", "poop", "vomit green", "vomit", "puke",
    "puke green", "bile", "dried blood", "blood", "bruise",
    # judgmental
    "nasty green", "boring green", "ugly brown", "ugly blue", "ugly purple", "ugly pink",
    "ugly yellow", "ugly green", "bland", "sickly yellow", "sick green", "sickly green",
    "icky green", "gross green", "weird green", "nice blue", "drab", "toxic green",
    "radioactive green", "poison green", "slime green", "murky green", "muddy green",
    "muddy yellow", "muddy brown", "dirty purple", "dirty blue", "dirty pink", "dirty orange",
    "dirty green", "dirty yellow",
    # a bare word or suffix is not a name
    "pale", "dark", "purply", "purpley", "pinky", "greyish", "reddish", "bluish", "yellowish",
    "brownish", "greenish", "pinkish", "purplish", "purpleish", "orangeish", "orangish", "tealish",
    # jokes and misspellings
    "light urple", "burple", "blurple", "perrywinkle", "liliac", "toupe", "terracota",
    "burnt siena", "ocre", "light lavendar", "forrest green", "kelley green", "manilla",
    "azul", "rosa", "aqua marine", "robin's egg", "robin egg blue",
    # repeats of a spaced name
    "light light green", "light light blue", "blue blue", "darkgreen", "darkblue", "lightgreen",
    "lightblue", "greenblue", "bluegreen", "greyblue", "bluegrey", "yellowgreen",
    # slang, brands and characters, and names that are a sentence
    "fluro green", "hospital green", "easter purple", "easter green", "windows blue",
    "tiffany blue", "kermit green", "barney", "barney purple", "barbie pink",
    "blue with a hint of purple", "really light blue", "pig pink",
    "camo", "camo green", "camouflage green", "military green", "army green",
}
RENAME = {"vermillion": "vermilion"}
EXTRA = [("International Orange", "FF4F00"), ("Klein Blue", "002FA7")]


def title(name):
    return " ".join(w if w == "and" else w[0].upper() + w[1:] for w in name.split(" "))


rows = []
seen = set()
for line in open(os.path.join(HERE, "rgb.txt")):
    if line.startswith("#"):
        continue
    name, value = line.split("\t")[:2]
    name = name.strip()
    seen.add(name)
    if name in DENY or "/" in name:
        continue
    rows.append((title(RENAME.get(name, name)), value.strip().lstrip("#").upper()))
missing = DENY - seen
assert not missing, f"denied names the survey does not have: {sorted(missing)}"
rows += EXTRA

with open(OUT, "w") as out:
    out.write("// Generated by tools/color-names/curate.py from the xkcd color survey\n")
    out.write("// (https://xkcd.com/color/rgb.txt, CC0). Edit the script, not this file.\n\n")
    out.write("extension ColorNames {\n")
    out.write(f"    /// {len(rows)} names, one per line: the name, a tab, the color as RRGGBB.\n")
    out.write('    static let table = """\n')
    for name, value in rows:
        out.write(f"{name}\t{value}\n")
    out.write('"""\n}\n')
print(f"{len(rows)} names → {os.path.relpath(OUT)}")
