import AppKit

// The Lodestar app icon and the website's marks, drawn from Mark.swift, never
// designed in an editor, so they are versioned, reproducible, and always the
// mark the menu bar draws. Run it through scripts/make-icon.sh, which
// compiles it beside Mark.swift; see that script for the options.
//
// The icon: the star with depth on charcoal that carries a little of the
// accent, on Apple's macOS grid (an 824-point plate, corner 185, on 1024),
// with the plate's faint top sheen and hairline edge, a soft shadow under
// the star, and the faintest wash of the accent behind it.

var accent = Mark.internationalOrange
var name = "international-orange"
var outputDir = ".build/mark"
var all = false
var arguments = Array(CommandLine.arguments.dropFirst())
while !arguments.isEmpty {
    let flag = arguments.removeFirst()
    switch flag {
    case "--accent":
        guard let value = arguments.first, let color = Mark.RGB(hex: value) else {
            FileHandle.standardError.write("--accent takes a hex color such as #FF4F00\n".data(using: .utf8)!)
            exit(64)
        }
        arguments.removeFirst()
        accent = color
        name = value.hasPrefix("#") ? String(value.dropFirst()).lowercased() : value.lowercased()
    case "--preset":
        guard let value = arguments.first, let preset = Mark.presets.first(where: { $0.name == value }) else {
            FileHandle.standardError.write("--preset takes one of: \(Mark.presets.map(\.name).joined(separator: ", "))\n".data(using: .utf8)!)
            exit(64)
        }
        arguments.removeFirst()
        accent = preset.color
        name = preset.name
    case "--out":
        outputDir = arguments.removeFirst()
    case "--all":
        all = true
    default:
        FileHandle.standardError.write("unknown option \(flag)\n".data(using: .utf8)!)
        exit(64)
    }
}

func writePNG(_ image: NSImage, to path: String, pixels: Int) {
    let rep = NSBitmapImageRep(bitmapDataPlanes: nil, pixelsWide: pixels, pixelsHigh: pixels,
                               bitsPerSample: 8, samplesPerPixel: 4, hasAlpha: true,
                               isPlanar: false, colorSpaceName: .deviceRGB,
                               bytesPerRow: 0, bitsPerPixel: 0)!
    NSGraphicsContext.saveGraphicsState()
    NSGraphicsContext.current = NSGraphicsContext(bitmapImageRep: rep)
    image.draw(in: NSRect(x: 0, y: 0, width: pixels, height: pixels))
    NSGraphicsContext.restoreGraphicsState()
    try! rep.representation(using: .png, properties: [:])!.write(to: URL(fileURLWithPath: path))
}

/// The website's data: every face with its fill, and the ground, so the
/// site's logo and touch icon are drawn from the same faces.
func siteData(accent: Mark.RGB) -> String {
    let ground = Mark.ground(accent: accent)
    let faces = Mark.faces.map { face in
        let points = face.points.map { String(format: "[%.4f,%.4f]", $0.x, $0.y) }.joined(separator: ",")
        return "{\"points\":[\(points)],\"fill\":\"\(Mark.fill(tone: face.tone, accent: accent).hex)\"}"
    }.joined(separator: ",\n    ")
    return """
    {
      "_": "Generated by scripts/make-icon.sh from Sources/LodestarCore/Mark.swift. Do not edit.",
      "accent": "\(accent.hex)",
      "ground": { "top": "\(ground.top.hex)", "bottom": "\(ground.bottom.hex)" },
      "faces": [
        \(faces)
      ]
    }

    """
}

/// The bundle's icon as Icon Composer's format: the plate a solid fill per
/// appearance, clay by day and Slip at night, and the mark one layer over
/// it with its own shadow. The system's glass and specular stay off, so
/// the icon is as flat as everything else Lodestar draws.
func iconJSON(clay: Mark.RGB, night: Mark.RGB) -> String {
    func srgb(_ c: Mark.RGB) -> String { String(format: "srgb:%.5f,%.5f,%.5f,1.00000", c.red, c.green, c.blue) }
    return """
    {
      "fill-specializations" : [
        { "value" : { "solid" : "\(srgb(clay))" } },
        { "appearance" : "dark", "value" : { "solid" : "\(srgb(night))" } }
      ],
      "groups" : [
        {
          "layers" : [
            { "glass" : false, "image-name" : "mark.png", "name" : "mark" }
          ],
          "shadow" : { "kind" : "none", "opacity" : 0 },
          "specular" : false,
          "translucency" : { "enabled" : false, "value" : 0 }
        }
      ],
      "supported-platforms" : { "squares" : "shared" }
    }

    """
}

func render(accent: Mark.RGB, into dir: String) {
    let iconset = "\(dir)/lodestar.iconset"
    try? FileManager.default.createDirectory(atPath: iconset, withIntermediateDirectories: true)
    let entries: [(pixels: Int, name: String)] = [
        (16, "icon_16x16"), (32, "icon_16x16@2x"), (32, "icon_32x32"), (64, "icon_32x32@2x"),
        (128, "icon_128x128"), (256, "icon_128x128@2x"), (256, "icon_256x256"), (512, "icon_256x256@2x"),
        (512, "icon_512x512"), (1024, "icon_512x512@2x"),
    ]
    // The .icns is the icon for systems before macOS 26, which show one
    // picture whatever the appearance: the clay one, the default.
    for entry in entries {
        writePNG(AppIconArt.image(canvas: CGFloat(entry.pixels), ground: .clay, accent: accent),
                 to: "\(iconset)/\(entry.name).png", pixels: entry.pixels)
    }
    writePNG(AppIconArt.image(canvas: 1024, ground: .clay, accent: accent), to: "\(dir)/preview-clay.png", pixels: 1024)
    writePNG(AppIconArt.image(canvas: 1024, ground: .night, accent: accent), to: "\(dir)/preview-night.png", pixels: 1024)
    let source = "\(dir)/Lodestar.icon"
    try? FileManager.default.createDirectory(atPath: "\(source)/Assets", withIntermediateDirectories: true)
    writePNG(AppIconArt.star(canvas: 1024, accent: accent), to: "\(source)/Assets/mark.png", pixels: 1024)
    try! iconJSON(clay: AppIconArt.plate(.clay).fill, night: AppIconArt.plate(.night).fill)
        .write(toFile: "\(source)/icon.json", atomically: true, encoding: .utf8)
    try! Mark.svg(accent: accent, size: 64, ground: true).write(toFile: "\(dir)/icon.svg", atomically: true, encoding: .utf8)
    try! Mark.svg(accent: accent, size: 64).write(toFile: "\(dir)/mark.svg", atomically: true, encoding: .utf8)
    try! siteData(accent: accent).write(toFile: "\(dir)/mark.json", atomically: true, encoding: .utf8)
    print("\(dir): iconset, Lodestar.icon, previews, icon.svg, mark.svg, mark.json")
}

if all {
    for preset in Mark.presets { render(accent: preset.color, into: "\(outputDir)/\(preset.name)") }
} else {
    render(accent: accent, into: "\(outputDir)/\(name)")
}
