import Foundation

/// The clipboard history, extracted pure: what may be recorded, what a clip
/// is, which slot a pin occupies, and what gets trimmed. The effectful half
/// — polling the pasteboard, writing files, synthesizing ⌘V — lives in the
/// app target. Everything here is deterministic and tested.
public enum Clipboard {
    /// What a clip is made of. `plain` is what a bare label pastes; `native`
    /// is what ⇧label pastes — the richest thing the source app offered,
    /// whether that is RTF, HTML, or something only Figma understands.
    public enum Kind: String, Codable, Equatable {
        case text
        case image
    }

    public struct Clip: Codable, Equatable {
        public let id: String
        public let kind: Kind
        public let created: Date
        /// The app that put it on the pasteboard, for recognition.
        public let sourceBundleID: String?
        public let sourceAppName: String?
        /// Rendered on the card and searched against — never the whole clip.
        public let preview: String
        /// Bytes on disk across every representation, for the size cap.
        public let bytes: Int
        /// Pasteboard types stored alongside the plain form, richest first.
        public let nativeTypes: [String]
        /// nil when the clip is not pinned; otherwise its permanent slot.
        public var pinnedSlot: Int?

        public init(id: String, kind: Kind, created: Date,
                    sourceBundleID: String?, sourceAppName: String?,
                    preview: String, bytes: Int,
                    nativeTypes: [String] = [], pinnedSlot: Int? = nil) {
            self.id = id
            self.kind = kind
            self.created = created
            self.sourceBundleID = sourceBundleID
            self.sourceAppName = sourceAppName
            self.preview = preview
            self.bytes = bytes
            self.nativeTypes = nativeTypes
            self.pinnedSlot = pinnedSlot
        }

        public var isPinned: Bool { pinnedSlot != nil }
        /// ⇧label differs from label only when the source offered more than
        /// plain text.
        public var hasNativeForm: Bool { !nativeTypes.isEmpty }
    }

    // MARK: - What may be recorded

    /// Pasteboard types that mark content as none of our business. A
    /// password manager sets the concealed type precisely so tools like this
    /// one look away; transient and auto-generated say the same in weaker
    /// words. Recording any of them once is a breach that cannot be undone,
    /// so this is checked before anything is read, let alone written.
    public static let refusedTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
    ]

    public enum Refusal: Equatable {
        case concealed(String)
        case excludedApp(String)
        case excludedPattern(String)
        case tooLarge(Int)
        case empty
    }

    /// Everything standing between the pasteboard and the disk. Order is
    /// deliberate: the cheapest and most sensitive checks first, so a
    /// concealed clip is refused before its content is ever examined.
    public static func refusal(types: [String],
                               sourceBundleID: String?,
                               text: String?,
                               bytes: Int,
                               excludedApps: Set<String>,
                               excludedPatterns: [String],
                               maxItemBytes: Int) -> Refusal? {
        if let concealed = types.first(where: { refusedTypes.contains($0) }) {
            return .concealed(concealed)
        }
        if let bundleID = sourceBundleID?.lowercased(), excludedApps.contains(bundleID) {
            return .excludedApp(bundleID)
        }
        if let text, !excludedPatterns.isEmpty {
            let haystack = text.lowercased()
            if let pattern = excludedPatterns.first(where: { haystack.contains($0.lowercased()) }) {
                return .excludedPattern(pattern)
            }
        }
        if bytes > maxItemBytes { return .tooLarge(bytes) }
        if let text, text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty, bytes == 0 {
            return .empty
        }
        return nil
    }

    /// The card's line of text: collapsed whitespace, bounded, so a clip of
    /// a whole file does not become a giant index entry.
    public static func preview(of text: String, limit: Int = 2000) -> String {
        let collapsed = text
            .replacingOccurrences(of: "\r\n", with: "\n")
            .trimmingCharacters(in: .whitespacesAndNewlines)
        return collapsed.count <= limit ? collapsed : String(collapsed.prefix(limit))
    }

    /// The recents alphabet: home row, left to right, so the keys under
    /// your fingers sit in the same order as the cards under your eyes.
    /// Its own alphabet, not the hints one — hint labels are arbitrary
    /// assignments to screen positions, these are ordinal.
    public static let recentLabels = Array("asdfghjkl").map(String.init)

    // MARK: - Pins

    /// Pins are slots, not a list. A slot's meaning must never change, or
    /// the blind paste that pins exist for never becomes automatic — the
    /// same consistent-mapping rule that governs every other lode gesture.
    /// So a new pin takes the lowest free slot, and unpinning leaves a hole
    /// rather than renumbering the survivors.
    public static let pinSlots = 5

    public static func lowestFreeSlot(taken: Set<Int>, slots: Int = pinSlots) -> Int? {
        (1...slots).first { !taken.contains($0) }
    }

    // MARK: - Retention

    /// What to drop, oldest first, until the store fits. Pins are exempt
    /// entirely — that is most of what pinning means.
    ///
    /// Two ceilings: the bytes the user chose, and an item count they never
    /// see. The count is a guard on the design rather than on them — the
    /// index is held in memory and rewritten on a coalesced timer, and a
    /// byte cap alone does not bound how many text clips fit under it.
    public static func trim(_ clips: [Clip],
                            maxBytes: Int,
                            maxItems: Int) -> [String] {
        let pinned = clips.filter(\.isPinned)
        var loose = clips.filter { !$0.isPinned }.sorted { $0.created > $1.created }

        var doomed: [String] = []
        if loose.count > maxItems {
            doomed += loose[maxItems...].map(\.id)
            loose = Array(loose[..<maxItems])
        }
        // Pinned bytes count toward the ceiling but can never be evicted, so
        // the loose clips absorb the whole overage.
        var total = pinned.reduce(0) { $0 + $1.bytes } + loose.reduce(0) { $0 + $1.bytes }
        while total > maxBytes, let oldest = loose.popLast() {
            doomed.append(oldest.id)
            total -= oldest.bytes
        }
        return doomed
    }

    /// Copying the same thing again is a new copy: it rises to the top and
    /// the source updates. Pasting never reorders — the list is your copy
    /// history, which is the only reading that stays true while you use it.
    public static func merging(_ existing: [Clip], with arrival: Clip) -> [Clip] {
        var out = existing
        if let index = out.firstIndex(where: { $0.id == arrival.id }) {
            let slot = out[index].pinnedSlot
            out.remove(at: index)
            var promoted = arrival
            promoted.pinnedSlot = slot
            out.insert(promoted, at: 0)
            return out
        }
        out.insert(arrival, at: 0)
        return out
    }

    /// Newest first, pins excluded — pins have their own zone and their own
    /// addresses, so a pinned clip never also occupies a recent card.
    public static func recents(_ clips: [Clip]) -> [Clip] {
        clips.filter { !$0.isPinned }.sorted { $0.created > $1.created }
    }

    public static func pins(_ clips: [Clip]) -> [Clip] {
        clips.filter(\.isPinned).sorted { ($0.pinnedSlot ?? 0) < ($1.pinnedSlot ?? 0) }
    }

    /// Substring, case-insensitive, over the stored preview — the same
    /// shape `web.routes` already uses, so it is one idea, not two.
    public static func search(_ clips: [Clip], query: String) -> [Clip] {
        let needle = query.trimmingCharacters(in: .whitespaces).lowercased()
        guard !needle.isEmpty else { return recents(clips) }
        return recents(clips).filter { $0.preview.lowercased().contains(needle) }
    }
}
