import Foundation

/// The clipboard history, extracted pure: what may be recorded, what a clip
/// is, which slot a pin occupies, and what gets trimmed. The effectful half
/// — polling the pasteboard, writing files, synthesizing ⌘V — lives in the
/// app target. Everything here is deterministic and tested.
public enum Clipboard {
    /// What a clip is made of. `plain` is what a bare label pastes; `native`
    /// is what ⇧label pastes — the richest thing the source app offered,
    /// whether that is RTF, HTML, or something only Figma understands.
    public enum Kind: String, Codable, Equatable {
        case text
        case image
    }

    public struct Clip: Codable, Equatable {
        public let id: String
        public let kind: Kind
        public let created: Date
        /// The app that put it on the pasteboard, for recognition.
        public let sourceBundleID: String?
        public let sourceAppName: String?
        /// Rendered on the card and searched against — never the whole clip.
        /// A var, because an image's caption grows once its text has been
        /// read, a beat after the card exists.
        public var preview: String
        /// Bytes on disk across every representation, for the size cap.
        public let bytes: Int
        /// The first item's pasteboard types, stored alongside its plain
        /// form, richest first.
        public let nativeTypes: [String]
        /// Every item after the first, by the types each one carries.
        ///
        /// A copy is not always one thing. Three files selected in Finder
        /// go on the pasteboard as three items, and a clip that kept only
        /// the first pasted one file where three were copied. The shape is
        /// lopsided because the first item's types were on disk under
        /// `nativeTypes` long before the rest were kept, and this decodes
        /// as absent for every clip written back then — a clip that will
        /// not decode takes the whole index down with it.
        public let otherItemTypes: [[String]]?
        /// nil when the clip is not pinned; otherwise its permanent slot.
        public var pinnedSlot: Int?
        /// The page a browser copy came from, host only — the address a
        /// hand remembers a clip by, "the one from GitHub" — read from the
        /// source-url type Chromium puts beside every copy. Never the path,
        /// and absent for every clip that did not come from a page.
        public var sourceHost: String?

        public init(id: String, kind: Kind, created: Date,
                    sourceBundleID: String?, sourceAppName: String?,
                    preview: String, bytes: Int,
                    nativeTypes: [String] = [], otherItemTypes: [[String]] = [],
                    pinnedSlot: Int? = nil, sourceHost: String? = nil) {
            self.id = id
            self.kind = kind
            self.created = created
            self.sourceBundleID = sourceBundleID
            self.sourceAppName = sourceAppName
            self.preview = preview
            self.bytes = bytes
            self.sourceHost = sourceHost
            self.nativeTypes = nativeTypes
            // Absent rather than empty for the single-item copy, which is
            // almost every copy: the index is rewritten on a timer for the
            // life of the app, and a key that says nothing is a key not
            // worth writing ten thousand times.
            self.otherItemTypes = otherItemTypes.isEmpty ? nil : otherItemTypes
            self.pinnedSlot = pinnedSlot
        }

        public var isPinned: Bool { pinnedSlot != nil }
        /// Every item's types, first to last — the whole copy, which is
        /// what a paste has to put back.
        public var itemTypes: [[String]] { [nativeTypes] + (otherItemTypes ?? []) }
        public var itemCount: Int { 1 + (otherItemTypes?.count ?? 0) }
        /// ⇧label differs from label only when the source offered more than
        /// plain text.
        public var hasNativeForm: Bool { itemTypes.contains { !$0.isEmpty } }
        /// What the card says it is holding, or nil for the ordinary copy
        /// of one thing. Files by name, because a copy of several things
        /// usually is files and "3 files" is what the hand remembers doing.
        public var itemsLabel: String? { Clipboard.itemsLabel(itemTypes: itemTypes) }
    }

    // MARK: - What may be recorded

    /// Pasteboard types that mark content as none of our business. A
    /// password manager sets the concealed type precisely so tools like this
    /// one look away; transient and auto-generated say the same in weaker
    /// words. Recording any of them once is a breach that cannot be undone,
    /// so this is checked before anything is read, let alone written.
    public static let refusedTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
    ]

    /// How many items one copy may bring into the history.
    ///
    /// A copy of a whole folder can put thousands of items on the
    /// pasteboard, and every one of them is a file written, bytes counted,
    /// and an index rewritten on a timer. Past this the copy is left alone
    /// entirely rather than kept in part: a card that pastes some of what
    /// you copied is worse than no card at all, because it looks like it
    /// worked.
    public static let maxItemsPerClip = 32

    public enum Refusal: Equatable {
        case concealed(String)
        case excludedApp(String)
        case excludedPattern(String)
        case tooLarge(Int)
        case tooManyItems(Int)
        case empty
    }

    /// The half of the verdict that can be reached from the pasteboard's
    /// type list and its owner alone — no byte of content required.
    ///
    /// This exists so the caller can honour the promise below literally.
    /// A password manager marks its clip concealed precisely so tools like
    /// this look away, and "look away" has to mean before the read, not
    /// before the write: content pulled into this process has already left
    /// the boundary the mark was asking us to respect.
    public static func refusalBeforeReading(types: [String],
                                            sourceBundleID: String?,
                                            excludedApps: Set<String>,
                                            itemCount: Int = 1) -> Refusal? {
        if let concealed = types.first(where: { refusedTypes.contains($0) }) {
            return .concealed(concealed)
        }
        if let bundleID = sourceBundleID?.lowercased(), excludedApps.contains(bundleID) {
            return .excludedApp(bundleID)
        }
        // How many items are on the board is metadata like the rest of
        // this, so the copy nobody can hold faithfully is refused without
        // a byte of it being read either.
        if itemCount > maxItemsPerClip { return .tooManyItems(itemCount) }
        return nil
    }

    /// Everything standing between the pasteboard and the disk. Order is
    /// deliberate: the cheapest and most sensitive checks first, so a
    /// concealed clip is refused before its content is ever examined.
    public static func refusal(types: [String],
                               sourceBundleID: String?,
                               text: String?,
                               bytes: Int,
                               excludedApps: Set<String>,
                               excludedPatterns: [String],
                               maxItemBytes: Int) -> Refusal? {
        if let early = refusalBeforeReading(types: types, sourceBundleID: sourceBundleID,
                                            excludedApps: excludedApps) {
            return early
        }
        if let text, !excludedPatterns.isEmpty {
            let haystack = text.lowercased()
            if let pattern = excludedPatterns.first(where: { haystack.contains($0.lowercased()) }) {
                return .excludedPattern(pattern)
            }
        }
        if bytes > maxItemBytes { return .tooLarge(bytes) }
        if let text, text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty, bytes == 0 {
            return .empty
        }
        return nil
    }

    // MARK: - A restore is not a copy

    /// Types a clipboard manager stamps on the previous contents when it
    /// puts them back after a paste of its own. The bytes are not a new
    /// copy — the card is already in the history — so the list must not
    /// reorder for them: copies reorder, pastes do not, and neither does
    /// a restore. A restore of something the history never saw is still
    /// recorded, because then it is news.
    public static let restoreTypes: Set<String> = ["com.raycast.RestoredType"]

    public static func isRestore(types: [String]) -> Bool {
        types.contains { restoreTypes.contains($0) }
    }

    // MARK: - Where a copy came from

    /// The pasteboard type Chromium browsers put beside a copy, carrying
    /// the page it was made on.
    public static let sourceURLType = "org.chromium.source-url"

    /// The host of a page, as the card shows it and the search reads it:
    /// lowercased, the leading www dropped. Nil for anything that is not
    /// a URL with a host — a path, a fragment, an empty string.
    public static func sourceHost(fromURL string: String?) -> String? {
        guard let string,
              let url = URL(string: string.trimmingCharacters(in: .whitespacesAndNewlines)),
              var host = url.host?.lowercased(), !host.isEmpty else { return nil }
        if host.hasPrefix("www.") { host.removeFirst(4) }
        return host.isEmpty ? nil : host
    }

    // MARK: - An image says what it shows

    /// An image card's preview: its size, and under it every line the
    /// recognizer read — what a screenshot of an error message is found
    /// by. The size line stays first so a card whose text arrives a beat
    /// later still reads as the same card.
    public static func imagePreview(width: Int, height: Int, text: String? = nil) -> String {
        let head = "image \(width)×\(height)"
        guard let text, !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
        else { return head }
        return head + "\n" + preview(of: text, limit: 1500)
    }

    /// An image card's caption, arriving a beat after the card: the size
    /// line it already had stays first, so the card is the card it was,
    /// and the text goes under it for the search to read.
    public static func captioned(_ preview: String, with text: String) -> String {
        let head = preview.split(separator: "\n", maxSplits: 1,
                                 omittingEmptySubsequences: false).first.map(String.init) ?? preview
        let body = self.preview(of: text, limit: 1500)
        return body.isEmpty ? head : head + "\n" + body
    }

    // MARK: - Pasting into a search

    /// What ⌘V puts into a search band: the pasteboard's text with every
    /// run of whitespace, newlines included, folded to one space, and cut
    /// to a length a band can hold. A band is one line; a pasted paragraph
    /// searches by its first two hundred characters.
    public static func pastedQuery(_ text: String, limit: Int = 200) -> String {
        let collapsed = text.split(whereSeparator: { $0.isWhitespace }).joined(separator: " ")
        return String(collapsed.prefix(limit))
    }

    // MARK: - A copy is its items

    /// The pasteboard's word for a file, which is what a copy of several
    /// things almost always holds.
    public static let fileURLType = "public.file-url"

    /// What a card says it is holding when one copy brought several things,
    /// and nil for the ordinary copy of one thing, which says nothing
    /// because there is nothing to say.
    public static func itemsLabel(itemTypes: [[String]]) -> String? {
        guard itemTypes.count > 1 else { return nil }
        let files = itemTypes.allSatisfy { $0.contains(fileURLType) }
        return "\(itemTypes.count) \(files ? "files" : "items")"
    }

    /// The bytes a copy is named by, so copying the same thing again lands
    /// on the card it already has instead of growing a second one.
    ///
    /// One item is hashed exactly as it always was — every clip already on
    /// disk was named that way, and changing it would give everything in a
    /// user's history a stranger's name the next time they copied it.
    /// Several items are length-prefixed rather than run together, so two
    /// files copied side by side can never hash as their contents joined.
    public static func identityData(items: [Data]) -> Data {
        guard items.count > 1 else { return items.first ?? Data() }
        var joined = Data()
        for item in items {
            var length = UInt64(item.count).littleEndian
            withUnsafeBytes(of: &length) { joined.append(contentsOf: $0) }
            joined.append(item)
        }
        return joined
    }

    // MARK: - Pasting into a terminal

    /// A terminal delivers a paste as bytes down a pty, and a pty has no way
    /// to carry an image — so ⌘V into one can never land a picture, however
    /// rich the pasteboard is.
    ///
    /// What every terminal *does* paste is text, and a path is text. The
    /// tools you run in one read the image back off it: Claude Code turns a
    /// pasted `.png` path into an attachment. So for an image into a
    /// terminal the clip also goes on the pasteboard as a file, and the path
    /// is what ⌘V delivers. Graphical apps never see this — they take the
    /// picture itself, which is what they can actually accept.
    public static let terminalBundleIDs: Set<String> = [
        "com.mitchellh.ghostty",
        "com.googlecode.iterm2",
        "com.apple.terminal",
        "org.alacritty",
        "io.alacritty",
        "net.kovidgoyal.kitty",
        "com.github.wez.wezterm",
        "dev.warp.warp-stable",
        "co.zeit.hyper",
        "com.raphaelamorim.rio",
    ]

    /// Only images, and only into a terminal: text pastes down a pty exactly
    /// as it should, so nothing changes for the common case.
    public static func pastesAsFilePath(kind: Kind, frontmostBundleID: String?) -> Bool {
        guard kind == .image, let id = frontmostBundleID?.lowercased() else { return false }
        return terminalBundleIDs.contains(id)
    }

    /// Extensions the far side will recognise as an image. A path only works
    /// if it is named like a picture — the reader checks the extension
    /// before it ever opens the file.
    public static let pasteableImageExtension = "png"

    /// The name Lodestar gives the files it hands to terminals.
    public static let handoverPrefix = "lodestar-"

    /// Is this clip merely one of those paths coming back to us?
    ///
    /// After a terminal paste the pasteboard holds our own file path, so the
    /// next launch — which reads whatever is already on the pasteboard —
    /// would file it as a clip. It is worth nothing to the user, and worse
    /// than nothing once the temp file behind it is pruned and the path
    /// pastes dead.
    public static func isOwnHandoverPath(_ text: String?, temporaryDirectory: String) -> Bool {
        guard let text else { return false }
        let path = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard path.hasPrefix(temporaryDirectory) else { return false }
        return (path as NSString).lastPathComponent.hasPrefix(handoverPrefix)
    }

    /// The card's line of text: collapsed whitespace, bounded, so a clip of
    /// a whole file does not become a giant index entry.
    public static func preview(of text: String, limit: Int = 2000) -> String {
        let collapsed = text
            .replacingOccurrences(of: "\r\n", with: "\n")
            .trimmingCharacters(in: .whitespacesAndNewlines)
        return collapsed.count <= limit ? collapsed : String(collapsed.prefix(limit))
    }

    /// ⌥⌫ — drop the last word, and any whitespace trailing it, the way
    /// every macOS text field does: "a big cat " and "a big cat" both
    /// become "a big ".
    public static func droppingLastWord(_ query: String) -> String {
        var remaining = Substring(query)
        while let last = remaining.last, last.isWhitespace { remaining = remaining.dropLast() }
        while let last = remaining.last, !last.isWhitespace { remaining = remaining.dropLast() }
        return String(remaining)
    }

    /// How long ago, in the shortest honest form. You reach for old clips
    /// temporally — "the one from this morning" — and a preview alone
    /// cannot say that.
    public static func age(of clip: Clip, now: Date = Date()) -> String {
        let seconds = max(0, now.timeIntervalSince(clip.created))
        if seconds < 45 { return "now" }
        if seconds < 3600 { return "\(Int(seconds / 60))m" }
        if seconds < 86_400 { return "\(Int(seconds / 3600))h" }
        return "\(Int(seconds / 86_400))d"
    }

    /// The recents alphabet: home row, left to right, so the keys under
    /// your fingers sit in the same order as the cards under your eyes.
    /// Its own alphabet, not the hints one — hint labels are arbitrary
    /// assignments to screen positions, these are ordinal.
    public static let recentLabels = Array("asdfghjkl").map(String.init)

    // MARK: - Pins

    /// Pins are slots, not a list. A slot's meaning must never change, or
    /// the blind paste that pins exist for never becomes automatic — the
    /// same consistent-mapping rule that governs every other lode gesture.
    /// So a new pin takes the lowest free slot, and unpinning leaves a hole
    /// rather than renumbering the survivors.
    public static let pinSlots = 5

    public static func lowestFreeSlot(taken: Set<Int>, slots: Int = pinSlots) -> Int? {
        (1...slots).first { !taken.contains($0) }
    }

    /// How many slots the column draws: every slot through the highest one
    /// in use, and one free slot after it, so the next pin's number is
    /// visible without four empty cards standing for slots nobody has
    /// reached. Positions never move — slots stack from the corner, and a
    /// drawn slot sits exactly where it always did.
    public static func pinSlotsToDraw(taken: Set<Int>, slots: Int = pinSlots) -> Int {
        min(slots, max(1, (taken.max() ?? 0) + 1))
    }

    // MARK: - Retention

    /// What to drop, oldest first, until the store fits. Pins are exempt
    /// entirely — that is most of what pinning means.
    ///
    /// Two ceilings: the bytes the user chose, and an item count they never
    /// see. The count is a guard on the design rather than on them — the
    /// index is held in memory and rewritten on a coalesced timer, and a
    /// byte cap alone does not bound how many text clips fit under it.
    public static func trim(_ clips: [Clip],
                            maxBytes: Int,
                            maxItems: Int) -> [String] {
        let pinned = clips.filter(\.isPinned)
        var loose = clips.filter { !$0.isPinned }.sorted { $0.created > $1.created }

        var doomed: [String] = []
        if loose.count > maxItems {
            doomed += loose[maxItems...].map(\.id)
            loose = Array(loose[..<maxItems])
        }
        // Pinned bytes count toward the ceiling but can never be evicted, so
        // the loose clips absorb the whole overage.
        var total = pinned.reduce(0) { $0 + $1.bytes } + loose.reduce(0) { $0 + $1.bytes }
        while total > maxBytes, let oldest = loose.popLast() {
            doomed.append(oldest.id)
            total -= oldest.bytes
        }
        return doomed
    }

    /// Copying the same thing again is a new copy: it rises to the top and
    /// the source updates. Pasting never reorders — the list is your copy
    /// history, which is the only reading that stays true while you use it.
    public static func merging(_ existing: [Clip], with arrival: Clip) -> [Clip] {
        var out = existing
        if let index = out.firstIndex(where: { $0.id == arrival.id }) {
            let slot = out[index].pinnedSlot
            out.remove(at: index)
            var promoted = arrival
            promoted.pinnedSlot = slot
            out.insert(promoted, at: 0)
            return out
        }
        out.insert(arrival, at: 0)
        return out
    }

    /// Newest first, pins excluded — pins have their own zone and their own
    /// addresses, so a pinned clip never also occupies a recent card.
    ///
    /// No sort: `merging` inserts every arrival at the front, so the list
    /// is newest-first by construction, and this runs on every keystroke
    /// of a strip search over a history capped at ten thousand. A test
    /// stands on the invariant so a future merge cannot quietly break it.
    public static func recents(_ clips: [Clip]) -> [Clip] {
        clips.filter { !$0.isPinned }
    }

    public static func pins(_ clips: [Clip]) -> [Clip] {
        clips.filter(\.isPinned).sorted { ($0.pinnedSlot ?? 0) < ($1.pinnedSlot ?? 0) }
    }

    /// How well a clip answers a query, or nil when it does not.
    ///
    /// Two tiers, because they mean different things. A literal hit is what
    /// you typed, sitting in the text — the strongest possible signal, and
    /// the earlier it sits the more the clip is *about* it. Failing that,
    /// the letters in order: this is what lets "gitcom" find a commit
    /// command, which is the whole reason to want more than substring.
    ///
    /// A subsequence over long text is permissive by nature, so it is scored
    /// far below any literal hit rather than mixed in with one. It also
    /// wants two characters: a single letter appears in order in nearly
    /// every clip ever copied, which is noise rather than a search.
    /// `needle` must already be lowercased and trimmed.
    public static func relevance(of preview: String, to needle: String) -> Double? {
        guard !needle.isEmpty else { return 0 }
        // One cheap pass gates both tiers: a literal hit is necessarily also
        // a subsequence, so anything this rejects cannot match either way.
        // It is what keeps the expensive search off the 99% of clips that
        // have nothing to do with the query. Only for an ASCII needle —
        // byte folding is not Unicode case folding, and the correct search
        // below is worth its cost on the rare query that needs it.
        let ascii = isASCII(needle)
        if ascii, !containsInOrder(needle, in: preview) { return nil }
        if let position = literalPosition(of: needle, in: preview) {
            return 1000 - Double(min(position, 800)) * 0.5
        }
        // An ASCII needle that reached this line already passed the gate's
        // scan, and a non-ASCII needle never owed it one — byte folding is
        // not Unicode case folding, and a gate that cannot fold Ü would
        // veto the very match the scorer below exists to find.
        guard needle.count >= 2 else { return nil }
        // Only the survivors pay for scoring. No length penalty either: a
        // clip is not worse for being long. The preview goes in as copied —
        // the scorer folds case once itself.
        return Fuzzy.score(query: needle, candidate: preview, lengthPenalty: 0)
    }

    /// Foundation's search, deliberately. A hand-rolled byte scan looked
    /// tempting for the hot loop, but a single-pointer one is wrong on
    /// repeats — it cannot find "aab" inside "aaab", because the failed
    /// third byte has already consumed the second "a" the match needed —
    /// and getting that right means KMP for a gain that measurement did not
    /// support. This allocates nothing over the haystack, and the cheap
    /// subsequence reject below is what actually keeps the loop fast.
    private static func literalPosition(of needle: String, in hay: String) -> Int? {
        guard let hit = hay.range(of: needle, options: [.caseInsensitive]) else { return nil }
        return hay.distance(from: hay.startIndex, to: hit.lowerBound)
    }

    /// Byte-wise, ASCII-folded, allocation free — and correct greedily,
    /// unlike substring: a subsequence never needs to give back a character
    /// it has already matched.
    ///
    /// This is the hot loop. It runs against every clip on every keystroke,
    /// and a history is capped at ten thousand previews of up to two
    /// thousand characters. Reaching `lowercased()` and `Array(candidate)`
    /// first — building two grapheme-cluster arrays per clip merely to
    /// discover it does not match — measured 3.6s on a full history.
    private static func isASCII(_ text: String) -> Bool {
        text.utf8.allSatisfy { $0 < 128 }
    }

    private static func containsInOrder(_ needle: String, in hay: String) -> Bool {
        let n = Array(needle.utf8)
        var matched = 0
        for byte in hay.utf8 {
            let folded = (byte >= 65 && byte <= 90) ? byte + 32 : byte
            if folded == n[matched] {
                matched += 1
                if matched == n.count { return true }
            }
        }
        return false
    }

    /// A host hit's score: under every literal hit in the preview, which
    /// is what you typed sitting in the text, and above a letters-in-order
    /// match, which is a guess.
    static let hostRelevance = 550.0

    /// How well a clip answers a query: its preview first, and then the
    /// page it came from — "github" finds the clips copied on GitHub even
    /// when none of them says so.
    public static func relevance(of clip: Clip, to needle: String) -> Double? {
        let text = relevance(of: clip.preview, to: needle)
        if let host = clip.sourceHost, !needle.isEmpty, host.contains(needle) {
            return max(text ?? 0, hostRelevance)
        }
        return text
    }

    /// Newest-first among equals, so an untyped strip and a searched one
    /// order the same way and the labels stay where the eye expects them.
    public static func search(_ clips: [Clip], query: String) -> [Clip] {
        let needle = query.trimmingCharacters(in: .whitespaces).lowercased()
        guard !needle.isEmpty else { return recents(clips) }
        return recents(clips)
            .enumerated()
            .compactMap { position, clip -> (Clip, Double, Int)? in
                guard let score = relevance(of: clip, to: needle) else { return nil }
                return (clip, score, position)
            }
            .sorted { $0.1 == $1.1 ? $0.2 < $1.2 : $0.1 > $1.1 }
            .map(\.0)
    }
}
